[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Martijn Pieters <mj@zopatista.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
bit-set = "0.5.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
regex = "1.4.2"
